spring:
  main:
    web-application-type: none

example:
  validation:
    hi: hello

# probably not necessary for normal configuration after autowiring figured out
#logging.level.org.springframework: DEBUG
